name: Promote Docker Image to Prod

on:
  push:
    branches:
      - main

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Promote Image
        run: |
          docker pull brentonmdunn/ride-bot-preprod:latest
          docker tag brentonmdunn/ride-bot-preprod:latest brentonmdunn/ride-bot:latest
          docker tag brentonmdunn/ride-bot-preprod:latest brentonmdunn/ride-bot:${{ github.sha }}
          docker push brentonmdunn/ride-bot:latest
          docker push brentonmdunn/ride-bot:${{ github.sha }}
